import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/header";
import { SITE_NAME } from "./constants/siteConstants";
import Footer from "./components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme={"light"}>
      <body className={inter.className}>
        <Header />
        <div className="h-screen mt-10 w-full"> {children}</div>
        <Footer />
      </body>
    </html>
  );
}
